### ISSUE TITLE
Format 2251-03 Toshiba 32GB drive. 

### ISSUE THREAD

**Issue by USBFormat** [soomeone/PsychsonMaker#2]
Hello, 
I saw that you have experience with the Phison 2251-03 chipset.  I couldn't figure out any other way to contact you so I stated an issue.  

I have a 32gb Toshiba drive I would like to flash the firmware to remove the write protection on. I have been trying to figure out the correct version of Mpall, Burner and Firmware the only thing I have been successful in is bricking three drives.  

Loading PsychsonMaker, it appears to be having difficulty reading the drive also. 
Displaying:
 FATAL: System.InvalidOperationException: DeviceIoControl failed: 0006
   at DriveCom.PhisonDevice._SendCommand(SafeFileHandle handle, Byte[] cmd, Byte[] data, Int32 bytesExpected)
   at DriveCom.PhisonDevice.SendCommand(Byte[] cmd, Int32 bytesExpected)
   at DriveCom.PhisonDevice.RequestVendorInfo()
   at DriveCom.PhisonDevice.GetChipType()
   at DriveCom.Startup._GetInfo()
   at DriveCom.Startup.Main(String[] args)

Here is the report of the drive from Chip Genius 
Description: [G:]USB Mass Storage Device(TOSHIBA TOSHIBA USB DRV)
Device Type:        Mass Storage Device

Protocal Version: USB 3.00
Current Speed: High Speed
Max Current: 504mA

USB Device ID: VID = 0930 PID = 1400

Device Vendor: TOSHIBA
Device Name: TOSHIBA USB DRV
Device Revision: 0100

Manufacturer: TOSHIBA
Product Model: TOSHIBA USB DRV
Product Revision: PMAP

Controller Vendor: Phison
Controller Part-Number: PS2251-03(PS2303) - F/W 01.11.10 [2014-07-04]
Flash ID code:      98DE9493 - Toshiba TC58NVG6DDJTA00 [MLC-16K]

Using Phison MPALL v3.63.0C-DL17  I am seeing an error of ID issue 0002 [98 DE 94 93 76 50 8]

Thanks for any help you can provide.

**Comment by USBFormat** [comment]
Here is the firmware I extracted from the drive. 
[fw 2251-03.zip](https://github.com/soomeone/PsychsonMaker/files/2224976/fw.2251-03.zip)
